# Generated by Django 5.1.7 on 2025-04-12 14:28
import os

from django.db import migrations
from django.utils import timezone
from dotenv import load_dotenv


def create_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    User = get_user_model()

    if User.objects.exists:
        return

    load_dotenv()

    superuser = User.objects.create_superuser(
        username=os.getenv("DJANGO_SUPERUSER_USERNAME"),
        email=os.getenv("DJANGO_SUPERUSER_EMAIL"),
        password=os.getenv("DJANGO_SUPERUSER_PASSWORD"),
        created_at=timezone.now(),
    )

    superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app_dj", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_superuser)]
