# Generated by Django 5.1.7 on 2025-04-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dj', '0003_articles_creator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
